## tasks/packages_debian.yml
---
- name: '[Debian] packages'
  ansible.builtin.apt:
    state: present
    name:
      - git
      - python3
      - python3-pip
      - "perl" ## Used for unit conversion in volume list helper.
      ## Required for FUSE mount ($ weed mount)
      - fuse3
      ## For s3 interaction:
      - 's3cmd' ## https://pkgs.org/download/s3cmd
      ## Used for offsite filermeta backup.
      - 'rclone'
      - 'rsync'
  when: ansible_facts['os_family'] == 'Debian'
